language: ruby
jdk:
  - oraclejdk7
  - openjdk6
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby-19mode
  - jruby-18mode
git:
  depth: 10
scala:
#  - 2.10.0
  - 2.9.2
#  - 2.9.1
#  - 2.8.1
install:
  - source ci-setup.sh
  - export JRUBY_OPTS="-J-XX:MaxPermSize=312m -J-Xmx700M"
  - export JAVA_OPTS="-Xmx700m -XX:MaxPermSize=312m"
script: rake ci
notifications:
  email:
    recipients:
      - commits@buildr.apache.org
      - donaldp@apache.org
      - peter@realityforge.org
    on_success: always
    on_failure: always
notifications:
  irc: "irc.freenode.org#buildr"
